### ISSUE TITLE
error in query with random

### ISSUE THREAD

**Issue by cocodrino** [alaisi/postgres.async#10] opened 2015-04-22 22:02 UTC
Hi, this code

```clojure
(!/<!! (<query!  db ["SELECT * FROM articles ORDER BY random() LIMIT 1"]))
```

give me this exception

=> #<IllegalArgumentException java.lang.IllegalArgumentException: No method in multimethod 'from-pg-value' for dispatch value: BOOL>

the query is correct (I just try it in the postgre and works) but seems than postgres.async cant interprete it well.

**Comment by alaisi** [comment] 2015-04-28 18:11
Thanks for the report.

The problem is not with random, but with boolean type. I'll submit a fix to the Java driver.

**Comment by alaisi** [comment] 2015-04-28 19:12
Tracked issue: https://github.com/alaisi/postgres-async-driver/issues/5

**Comment by alaisi** [comment] 2015-05-08 18:47
Fixed in release 0.5.0

**Closed by alaisi** 2015-05-08 18:47 UTC

**Comment by cocodrino** [comment] 2015-05-10 02:18
thanks :+1:
